src = $(wildcard *.c)
obj = $(src:.c=.o)

all: $(obj)
	src = $(wildcard *.c)
obj = $(src:.c=.o)

LDFLAGS = -lGL -lglut -lpng -lz -lm

myprog: $(obj)
    $(CC) -o $@ $^ $(LDFLAGS)

.PHONY: clean
clean:
    rm -f $(obj) myprog
    $(CC) -o $@ $^

.PHONY: clean
clean:
    rm -f $(obj) 



.PHONY: clean
all:	*.c
	for filename in ./*.c; do
	        riscv64-unknown-elf-gcc -march=rv64imafd -mcmodel=medany -fomit-frame-pointer -fno-strict-aliasing -fno-builtin -c -o $filename.o $filename
        	riscv64-unknown-elf-ld $filename.o -T link.ld -o $filename.riscv
	done
clean:
	rm *.o
	rm *.riscv
